//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceToken2.Web.wsServicio {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsServicio.wsClientesSoap")]
    public interface wsClientesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje autenticaUsuarioRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autenticaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceToken2.Web.wsServicio.autenticaUsuarioResponse autenticaUsuario(WebServiceToken2.Web.wsServicio.autenticaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autenticaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceToken2.Web.wsServicio.autenticaUsuarioResponse> autenticaUsuarioAsync(WebServiceToken2.Web.wsServicio.autenticaUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje dsConsultaClientesRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dsConsultaClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceToken2.Web.wsServicio.dsConsultaClientesResponse dsConsultaClientes(WebServiceToken2.Web.wsServicio.dsConsultaClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dsConsultaClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceToken2.Web.wsServicio.dsConsultaClientesResponse> dsConsultaClientesAsync(WebServiceToken2.Web.wsServicio.dsConsultaClientesRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class classSeguridad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stTokenField;
        
        private string autenticaTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string stToken {
            get {
                return this.stTokenField;
            }
            set {
                this.stTokenField = value;
                this.RaisePropertyChanged("stToken");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string autenticaToken {
            get {
                return this.autenticaTokenField;
            }
            set {
                this.autenticaTokenField = value;
                this.RaisePropertyChanged("autenticaToken");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticaUsuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class autenticaUsuarioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad;
        
        public autenticaUsuarioRequest() {
        }
        
        public autenticaUsuarioRequest(WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad) {
            this.classSeguridad = classSeguridad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticaUsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class autenticaUsuarioResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string autenticaUsuarioResult;
        
        public autenticaUsuarioResponse() {
        }
        
        public autenticaUsuarioResponse(WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad, string autenticaUsuarioResult) {
            this.classSeguridad = classSeguridad;
            this.autenticaUsuarioResult = autenticaUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dsConsultaClientes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class dsConsultaClientesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdPais;
        
        public dsConsultaClientesRequest() {
        }
        
        public dsConsultaClientesRequest(WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad, int IdPais) {
            this.classSeguridad = classSeguridad;
            this.IdPais = IdPais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dsConsultaClientesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class dsConsultaClientesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet dsConsultaClientesResult;
        
        public dsConsultaClientesResponse() {
        }
        
        public dsConsultaClientesResponse(WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad, System.Data.DataSet dsConsultaClientesResult) {
            this.classSeguridad = classSeguridad;
            this.dsConsultaClientesResult = dsConsultaClientesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsClientesSoapChannel : WebServiceToken2.Web.wsServicio.wsClientesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsClientesSoapClient : System.ServiceModel.ClientBase<WebServiceToken2.Web.wsServicio.wsClientesSoap>, WebServiceToken2.Web.wsServicio.wsClientesSoap {
        
        public wsClientesSoapClient() {
        }
        
        public wsClientesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsClientesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsClientesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsClientesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceToken2.Web.wsServicio.autenticaUsuarioResponse WebServiceToken2.Web.wsServicio.wsClientesSoap.autenticaUsuario(WebServiceToken2.Web.wsServicio.autenticaUsuarioRequest request) {
            return base.Channel.autenticaUsuario(request);
        }
        
        public string autenticaUsuario(ref WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad) {
            WebServiceToken2.Web.wsServicio.autenticaUsuarioRequest inValue = new WebServiceToken2.Web.wsServicio.autenticaUsuarioRequest();
            inValue.classSeguridad = classSeguridad;
            WebServiceToken2.Web.wsServicio.autenticaUsuarioResponse retVal = ((WebServiceToken2.Web.wsServicio.wsClientesSoap)(this)).autenticaUsuario(inValue);
            classSeguridad = retVal.classSeguridad;
            return retVal.autenticaUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceToken2.Web.wsServicio.autenticaUsuarioResponse> WebServiceToken2.Web.wsServicio.wsClientesSoap.autenticaUsuarioAsync(WebServiceToken2.Web.wsServicio.autenticaUsuarioRequest request) {
            return base.Channel.autenticaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceToken2.Web.wsServicio.autenticaUsuarioResponse> autenticaUsuarioAsync(WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad) {
            WebServiceToken2.Web.wsServicio.autenticaUsuarioRequest inValue = new WebServiceToken2.Web.wsServicio.autenticaUsuarioRequest();
            inValue.classSeguridad = classSeguridad;
            return ((WebServiceToken2.Web.wsServicio.wsClientesSoap)(this)).autenticaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceToken2.Web.wsServicio.dsConsultaClientesResponse WebServiceToken2.Web.wsServicio.wsClientesSoap.dsConsultaClientes(WebServiceToken2.Web.wsServicio.dsConsultaClientesRequest request) {
            return base.Channel.dsConsultaClientes(request);
        }
        
        public System.Data.DataSet dsConsultaClientes(ref WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad, int IdPais) {
            WebServiceToken2.Web.wsServicio.dsConsultaClientesRequest inValue = new WebServiceToken2.Web.wsServicio.dsConsultaClientesRequest();
            inValue.classSeguridad = classSeguridad;
            inValue.IdPais = IdPais;
            WebServiceToken2.Web.wsServicio.dsConsultaClientesResponse retVal = ((WebServiceToken2.Web.wsServicio.wsClientesSoap)(this)).dsConsultaClientes(inValue);
            classSeguridad = retVal.classSeguridad;
            return retVal.dsConsultaClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceToken2.Web.wsServicio.dsConsultaClientesResponse> WebServiceToken2.Web.wsServicio.wsClientesSoap.dsConsultaClientesAsync(WebServiceToken2.Web.wsServicio.dsConsultaClientesRequest request) {
            return base.Channel.dsConsultaClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceToken2.Web.wsServicio.dsConsultaClientesResponse> dsConsultaClientesAsync(WebServiceToken2.Web.wsServicio.classSeguridad classSeguridad, int IdPais) {
            WebServiceToken2.Web.wsServicio.dsConsultaClientesRequest inValue = new WebServiceToken2.Web.wsServicio.dsConsultaClientesRequest();
            inValue.classSeguridad = classSeguridad;
            inValue.IdPais = IdPais;
            return ((WebServiceToken2.Web.wsServicio.wsClientesSoap)(this)).dsConsultaClientesAsync(inValue);
        }
    }
}
